### PR TITLE
meta-boundary: move specific layers to dynamic-layers

### PR DESCRIPTION
**Pull request by texierp**
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

### CODE REVIEW

**Comment by texierp** [comment]
ping ?

**Comment by texierp** [comment]
Any update ?

**Comment by texierp** [comment]
@chrisdimich, can you consider this PR ?

This one fixes:

```
ERROR: ParseError at /home/bdx-iot/mender/build/../sources/meta-boundary/recipes-qt/images/boundary-b2qt-embedded-qt5-image.bb:4: Could not include required file recipes-qt/images/b2qt-embedded-qt5-image.bb
```

**Comment by gibsson** [comment]
@chrisdimich please review this change, thanks!

**Comment by chrisdimich** [comment]
@texierp sorry for the delay on this. Can you please split up the network-layer commits from the qt ones and also please use "b2qt" instead of "qt5-layer" as these images are based on images in meta-boot2qt.

**Comment by texierp** [comment]
Thanks @chrisdimich , ok no problem. I wil close this PR for another one (target master instead) and then we will are able to cherry-pick.

**Pull request closed without merging**
